apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hugo-blog
  name: blog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hugo-blog
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hugo-blog
    spec:
      containers:
      - image: hryuk/hryuk.dev:latest
        imagePullPolicy: Always
        name: hugo-blog
        ports:
        - containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
spec:
  type: NodePort
  selector:
    app: hugo-blog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31080

